services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: practice
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
